---
micronaut:
  server:
    port: 8888
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:8080
  http:
    client:
      read-timeout: 30s
      follow-redirects: true
  application:
    name: basket-watch-backend
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:static
        mapping: "/static/**"
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/basket-watch
    driverClassName: org.postgresql.Driver
    username: basket-watch
    password: basket-watch
---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
---
basket-watch:
  job:
    basket-price-update:
      cron: 0 0 5 * * ?
    basket-delete:
      cron: 0 0 3 * * SUN
      basket-validity-in-weeks: 24
    item-price-update:
      cron: 0 0 1 * * ?
    notification:
      cron: 0 0 8 * * ?
  mail:
    from: basket-watch-info@siimp.ee
    from-personal: Basket-Watch (no-reply)
    smtp-host: 127.0.0.1
