---
micronaut:
  server:
    port: 8888
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:8080
  http:
    client:
      read-timeout: 30s
      follow-redirects: true
  application:
    name: basket-watch-backend
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/basket-watch
    driverClassName: org.postgresql.Driver
    username: basket-watch
    password: basket-watch
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

basket-watch:
  job:
    basket-price-update:
      cron: 0 0 2 * * ?
    basket-delete:
      cron: 0 0 3 * * SUN
      basket-validity-in-weeks: 8
    item-price-update:
      cron: 0 0 5 * * ?